### ISSUE TITLE
General layout - Desktop

### ISSUE THREAD

**Issue by pzwsk** [NaturalSolutions/cites#4]
Voici une proposition

Page de recherche sans résultats
![image](https://user-images.githubusercontent.com/2378439/46866907-7e1ff180-ce23-11e8-93d5-178ae82f8639.png)

**Comment by pzwsk** [comment]
Page de recherche avec résultats

![image](https://user-images.githubusercontent.com/2378439/46866951-9d1e8380-ce23-11e8-91f2-10e781713aaf.png)

**Comment by pzwsk** [comment]
Les informations sur classement CITES sont renvoyées en bas de page au dessus du footer.

Qu'en pensez vous ?

**Comment by ktalbi** [comment]
Ok. Footer avec fond blanc.

**Comment by ktalbi** [comment]
Pour le logo, on ne garde que l’éléphant ? le cercle est de même couleur que celle du fond.

**Comment by pzwsk** [comment]
Oui faisons ça, merci.
